- name: Install gnupg and pinentry
  pacman:
    name: "{{item}}"
    state: present
  with_items:
    - gnupg
    - pinentry
    - gtk2

- name: Create GPG directory
  file:
    path: "/home/{{system.user}}/.gnupg"
    state: directory
    owner: "{{system.user}}"
    mode: 0700

- name: Import user GPG configurations
  template:
    src: "./files/gpg/{{item}}"
    dest: "/home/{{system.user}}/.gnupg/{{item}}"
  with_items:
    - gpg.conf
    - gpg-agent.conf

- name: Retrieve user GPG key
  become: yes
  become_user: "{{system.user}}"
  command: "gpg --recv {{pgp.user_key}}"

- name: Copy GPG trust
  copy:
    src: ./files/gpg/trust
    dest: "/home/{{system.user}}/.gnupg/.import_trust"
    owner: "{{system.user}}"
    mode: 0600

- name: Trust user key 
  become: yes
  become_user: "{{system.user}}"
  command: "gpg --import-ownertrust /home/{{system.user}}/.gnupg/.import_trust"

- name: Configure git to use GPG for signing commits
  become: yes
  become_user: "{{system.user}}"
  git_config:
    name: commit.gpgsign
    scope: global
    value: true
