- hosts: local
  connection: local
  tasks:
    - include_vars:
        file: vars.yml
    - import_tasks: tasks/core.yml
    - import_tasks: tasks/network/core.yml
    - import_tasks: tasks/code/languages.yml
    - import_tasks: tasks/gui/xorg.yml
    - import_tasks: tasks/gui/i3.yml
    - import_tasks: tasks/gui/rofi.yml
    - import_tasks: tasks/gui/termite.yml
