- hosts: local
  connection: local
  tasks:
    - include_vars:
        file: vars.yml
    - import_tasks: tasks/core.yml
    - import_tasks: tasks/network/core.yml
    - import_tasks: tasks/code/languages.yml
