- name: Install Core Software
  pacman: 
    name: git, vim, base-devel

- name: Create User Account
  user:
    name: "{{ system.user }}"
    password: "{{ system.password }}"

- name: Give User Sudo Access
  lineinfile:
    path: /etc/sudoers
    line: "{{ system.user }} ALL=(ALL) ALL"

- name: Configure Git Name
  become: yes
  become_user: "{{ system.user }}"
  git_config:
    name: user.name
    scope: global
    value: "{{ git.name }}"

- name: Configure Git Email
  become: yes
  become_user: "{{ system.user }}"
  git_config:
    name: user.email
    scope: global
    value: "{{ git.email }}"
