- name: Install gnome keyring and libsecret
  pacman:
    name: gnome-keyring, libsecret

- name: Add gnome keyring to PAM auth
  lineinfile:
    path: "/etc/pam.d/login"
    insertafter: "^auth.*"
    line: "auth optional pam_gnome_keyring.so"

- name: Add gnome keyring to PAM session
  lineinfile:
    path: "/etc/pam.d/login"
    insertafter: "^session.*"
    line: "session optional pam_gnome_keyring.so auto_start"

- name: Add gnome-keyring to xinitrc
  lineinfile:
    path: "/home/{{system.user}}/.xinitrc"
    insertbefore: BOF
    line: "eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets)"
