- name: Install media applications
  pacman:
    name: vlc

- name: Install Spotify
  become: yes
  become_user: aur_builder
  aur:
    name: spotify

- name: Install playerctl
  pacman:
    name: playerctl
