- name: Install Rofi
  pacman:
    name: rofi

- name: Make config directory for Rofi
  file:
    path: "/home/{{ system.user }}/.config/rofi"
    state: directory
    owner: "{{ system.user }}"
    mode: 0755

- name: Deploy Rofi Config
  copy:
    src: ./files/gui/rofi
    dest: "/home/{{ system.user }}/.config/rofi/config"
    owner: "{{ system.user }}"
    mode: 0644
