- name: Install termite
  pacman:
    name: termite
    state: present

- name: Create termite config directory
  file:
    path: "/home/{{system.user}}/.config/termite"
    state: directory
    owner: "{{system.user}}"
    mode: 0755

- name: Copy termite config
  copy:
    src: ./files/gui/termite
    dest: "/home/{{system.user}}/.config/termite/config"
    owner: "{{system.user}}"
    mode: 0600

