- name: Add xinit to fish config
  blockinfile:
    path: "/home/{{system.user}}/.config/fish/config.fish"
    insertafter: EOF
    marker: "# {mark} XINIT AUTOMATIC LAUNCH"
    block: |
      # Start X at login
      if status is-login
        if test -z "$DISPLAY" -a $XDG_VTNR = 1
          exec startx -- -keeptty
        end
      end
